apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: app-is-bc
message: |-
  S2I docker builder
metadata:
  annotations:
    description: |-
      S2I docker builder
    iconClass: acorn
    openshift.io/display-name: S2I docker builder
  name: app-is-bc
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${BC_IS_NAME}"
  spec:
    tags:
    - from:
        kind: DockerImage
        name: "${DOCKER_REGISTRY}${DOCKER_IMAGE_NAME}"
      name: "${DOCKER_IMAGE_TAG}"
      importPolicy:
        scheduled: true
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "${BC_IS_NAME}"
  spec:
    runPolicy: "Serial"
    source:
      git:
        uri: "${GIT_REPO}"
        ref: "${GIT_REF}"
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "${S2I_BUILDER_ISTAG}"
          namespace: openshift
    output:
      to:
        kind: "DockerImage"
        name: "${DOCKER_REGISTRY}${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
      pushSecret:
        name: docker-io
parameters:
- description: Name for BC and IS
  displayName: The name for the BC and IS
  name: BC_IS_NAME
  required: true
- description: Docker registry
  displayName: Docker registry to where to push the docker image
  name: DOCKER_REGISTRY
  required: true
- description: Docker image name
  displayName: Docker image name
  name: DOCKER_IMAGE_NAME
  required: true
- description: Docker image tag
  displayName: Docker image tag
  name: DOCKER_IMAGE_TAG
  required: true
- description: GIT URL
  displayName: The GIT repo URL
  name: GIT_REPO
  required: true
- description: GIT REF
  displayName: Git commit or git branch or git tag
  name: GIT_REF
  required: true
- description: S2I build image tag name
  displayName: S2I build image tag name
  name: S2I_BUILDER_ISTAG
  required: true
