kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "coreapitest"
spec:
  source:
    git:
      uri: "https://github.com/Dimss/toltask.git"
      ref: "master"
    contextDir: "coreapitest"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile:
      env:
      - name: "APP_NAME"
        value: "coreapitest"
      - name: "S2I_BUILD_IMAGE"
        value: "dotnet:2.1"
      - name: "DOCKER_IMAGE_PREFIX"
        value: "dimssss"
      - name: "DOCKER_REGISTRY"
        value: "docker.io"
    type: JenkinsPipeline
