kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "coreapitest"
spec:
  source:
    git:
      uri: "http://gitlab.sales.lab.tlv.redhat.com/root/coreapitest.git"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile:
      env:
      - name: "GOVIL_APP_NAME"
        value: "coreapitest"
      - name: "S2I_BUILD_IMAGE"
        value: "dotnet:2.1"
      - name: "DOCKER_IMAGE_PREFIX"
        value: "dimssss"
      - name: "DOCKER_REGISTRY"
        value: "docker.io"
    type: JenkinsPipeline
